#spring.main.allow-bean-definition-overriding=true
spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  #  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_db
#    username: root
#    password:
#
#  jpa:
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
  mvc:
    problemdetails:
       enabled: true

  r2dbc:
    url: r2dbc:mysql://localhost:3306/test_db
    username: root
    password:
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S


#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    distribution:
#      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99
#      percentiles-histogram.http.server.requests: true
#      sla.http.server.requests: 1ms, 10ms, 100ms
#    enable.http.server.requests: true
#    export.prometheus.enabled: true

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
    loggers:
      enabled: true
  metrics:
#    distribution:
#      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99
#      percentiles-histogram.http.server.requests: true
#      sla.http.server.requests: 1ms, 10ms, 100ms
    enable.http.server.requests: true
    export.prometheus.enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true